# list of jobs to be exported and their mapping to job type
jobFilter:  
# - jobName: Data-Match 1 Commit
#   jobType: FETCH
# - jobName: Data-Match 2 Assemble
#   jobType: BUILD
# - jobName: Data-Match-Installer 3 Assemble Ansible
#   jobType: BUILD
 - jobName: Data-Match-Installer 4 Deploy
   jobType: DEPLOY
# - jobName: Database 1 Download
#   jobType: BUILD
 - jobName: Database 2 Deploy
   jobType: DEPLOY

# job name to pipeline mapping 
jobPipeline:
    Data-Match 1 Commit: Data-Match
    Data-Match 2 Assemble: Data-Match
    Data-Match-Installer 3 Assemble Ansible: Data-Match
    Data-Match-Installer 4 Deploy: Data-Match
    Database 1 Download: Database
    Database 2 Deploy: Database

# job stage is defined by the suffix of the job name
jobStage:
 - suffix: "Commit"
   stage: "BUILD"
 - suffix: "Assemble"
   stage: "BUILD"
 - suffix: "Ansible"
   stage: "BUILD"
 - suffix: "Deploy"
   stage: "DEPLOY"
 - suffix: "Download"
   stage: "DOWNLOAD"

