# list of jobs to be exported and their mapping to job type
jobFilter:  
 - jobName: DEVOPS-R4.5-CODAR-PACKAGE-DEPLOY
   jobType: DEPLOY
 - jobName: DEVOPS-R4.5-ALM-UFT-PC-TEST-MT
   jobType: TEST
 - jobName: DEVOPS-R4.5-ALM-UFT-PC-TEST-JAVA
   jobType: TEST
 - jobName: DEVOPS-R4.5-ALM-UFT-PC-TEST-DOTNET
   jobType: TEST
 - jobName: DEVOPS-R4.5-JENKINS-iBank-GIT-JAVA
   jobType: BUILD
 - jobName: DEVOPS-R4.5-BUILD-iBank-TFS-DOTNET
   jobType: BUILD

# job name to pipeline mapping 
jobPipeline:
    DEVOPS-CODAR-R4.5-1-BUILD: CODAR-MT
    DEVOPS-CODAR-R4.5-1-BUILD-JAVA: JAVA
    DEVOPS-CODAR-R4.5-1-BUILD-DOTNET: DOTNET
    DEVOPS-R4.5-DOCKER-1-DEV: DOCKER
    DEVOPS-JAVA-E2E-R4.5-1-BUILD: JAVA-E2E

# job stage is defined by the suffix of the job name
jobStage:
 - suffix: "-BUILD" 
   stage: "BUILD"
 - suffix: "TFS-DOTNET" 
   stage: "BUILD"
 - suffix: "-STG" 
   stage: "STG"
 - suffix: "-DV-INT" 
   stage: "DEV"
 - suffix: "-DEV" 
   stage: "DEV"
 - suffix: "-QA" 
   stage: "QA"
 - suffix: "-PROD" 
   stage: "PROD"
 - suffix: "-TEST" 
   stage: "TEST"
